POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "abc",
  "email": "abc6@def.ghi",
  "post": {
    "title": "post title"
  },
  "profile": {
    "bio": "profile bio"
  }
}
